"""Isolated Phase 1 Model Lab infrastructure.

Nothing in this package is connected to the production ``v04_expected_pe``
path.  ``true_fair_pe`` is accepted only by evaluation APIs.
"""

from .analysis import (
    ORACLE_DISAGREEMENT_LOG_TOLERANCE,
    build_leaderboard,
    oracle_complementarity,
    pareto_frontier,
)
from .baselines import HistoricalGeometricMeanPE
from .contracts import (
    EVALUATION_ONLY_TRUTH_COLUMN,
    DEFAULT_MODEL_IDENTITY_COLUMNS,
    FEATURE_AUDIT_STATUSES,
    FEATURE_FAMILIES,
    MODEL_CONTROL_COLUMNS,
    ContractError,
    FeatureAuditStatus,
    FeatureFamily,
    FeatureMetadata,
    FitContext,
    ModelMetadata,
    PEModel,
    PredictContext,
    validate_feature_frame,
    validate_model_call,
)
from .dataset import (
    CANONICAL_IDENTITY_COLUMNS,
    CANONICAL_INPUT_COLUMNS,
    DEFAULT_IDENTITY_COLUMNS,
    FORMAL_EVALUATION_START,
    PIT_CUTOFF_POLICY_IDS,
    PIT_LONG_SIDECAR_COLUMNS,
    PIT_SIDECAR_SERIALIZATION,
    PITFeatureSidecarSelection,
    PreparedModelInput,
    VerifiedPITSidecar,
    apply_identical_common_mask,
    attach_prediction_identity,
    merge_evaluation_truth,
    merge_pit_feature_sidecar,
    load_verified_pit_feature_sidecar,
    prepare_pit_feature_sidecar_asof,
    prepare_evaluation_truth,
    prepare_model_input,
)
from .evaluator import SUMMARY_COLUMNS, EvaluationResult, evaluate_fair_predictions
from .experiment import DeterministicExperimentLogger, ExperimentEvent, ExperimentLogError
from .folds import PITFold, PITFoldSpec, fold_manifest, generate_pit_folds, iter_fold_frames
from .matrices import (
    MatrixArtifacts,
    OOSMatrices,
    ParquetUnavailableError,
    canonicalize_oos_matrices,
    write_oos_matrices,
)
from .registry import (
    HELDOUT_STATUSES,
    LOCKED_STATUSES,
    MODEL_STATUSES,
    MODEL_TRACKS,
    MODEL_TRACK_SEMANTICS,
    TUNING_STATUSES,
    FeatureRegistration,
    ModelRegistration,
    RegistryError,
    RegistryPaths,
    RegistrySnapshot,
    append_feature_registration,
    append_model_registration,
    feature_registry_json_schema,
    load_feature_registry,
    load_model_registry,
    load_model_registry_history,
    model_registry_json_schema,
    validate_registry_cross_references,
    write_feature_registry,
    write_immutable_schema,
    write_model_registry,
)

__all__ = [
    "CANONICAL_IDENTITY_COLUMNS",
    "CANONICAL_INPUT_COLUMNS",
    "DEFAULT_IDENTITY_COLUMNS",
    "EVALUATION_ONLY_TRUTH_COLUMN",
    "DEFAULT_MODEL_IDENTITY_COLUMNS",
    "FEATURE_AUDIT_STATUSES",
    "FEATURE_FAMILIES",
    "MODEL_CONTROL_COLUMNS",
    "FORMAL_EVALUATION_START",
    "PIT_CUTOFF_POLICY_IDS",
    "PIT_LONG_SIDECAR_COLUMNS",
    "PIT_SIDECAR_SERIALIZATION",
    "PITFeatureSidecarSelection",
    "ContractError",
    "DeterministicExperimentLogger",
    "EvaluationResult",
    "ExperimentEvent",
    "ExperimentLogError",
    "FeatureMetadata",
    "FeatureAuditStatus",
    "FeatureFamily",
    "FeatureRegistration",
    "FitContext",
    "HistoricalGeometricMeanPE",
    "HELDOUT_STATUSES",
    "LOCKED_STATUSES",
    "MatrixArtifacts",
    "ModelMetadata",
    "ModelRegistration",
    "MODEL_STATUSES",
    "MODEL_TRACKS",
    "MODEL_TRACK_SEMANTICS",
    "OOSMatrices",
    "ORACLE_DISAGREEMENT_LOG_TOLERANCE",
    "PEModel",
    "PITFold",
    "PITFoldSpec",
    "ParquetUnavailableError",
    "PredictContext",
    "PreparedModelInput",
    "VerifiedPITSidecar",
    "RegistryError",
    "RegistryPaths",
    "RegistrySnapshot",
    "SUMMARY_COLUMNS",
    "TUNING_STATUSES",
    "append_feature_registration",
    "append_model_registration",
    "apply_identical_common_mask",
    "attach_prediction_identity",
    "build_leaderboard",
    "canonicalize_oos_matrices",
    "evaluate_fair_predictions",
    "feature_registry_json_schema",
    "fold_manifest",
    "generate_pit_folds",
    "iter_fold_frames",
    "load_feature_registry",
    "load_model_registry",
    "load_model_registry_history",
    "merge_evaluation_truth",
    "merge_pit_feature_sidecar",
    "load_verified_pit_feature_sidecar",
    "model_registry_json_schema",
    "oracle_complementarity",
    "pareto_frontier",
    "prepare_evaluation_truth",
    "prepare_model_input",
    "prepare_pit_feature_sidecar_asof",
    "validate_feature_frame",
    "validate_model_call",
    "validate_registry_cross_references",
    "write_feature_registry",
    "write_immutable_schema",
    "write_model_registry",
    "write_oos_matrices",
]
