"""Factory-only executable nested chronological OOF plans."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any

import numpy as np
import pandas as pd

from ..folds import PITFoldSpec, generate_pit_folds
from .authorization import StructuralExecutionAuthorization
from .contracts import (
    STRUCTURAL_DESIGN_SHA256,
    StructuralContractError,
    canonical_json_bytes,
    logical_frame_sha256,
    normalize_dates,
    require_sha256,
    sha256_bytes,
)


NESTED_FOLD_SPEC = PITFoldSpec(
    min_train_sessions=252,
    max_train_sessions=1008,
    test_sessions=21,
    step_sessions=21,
    embargo_sessions=0,
    allow_partial_final_test=False,
)
FORMAL_OUTER_FOLD_SPEC = PITFoldSpec(
    min_train_sessions=252,
    max_train_sessions=1008,
    test_sessions=21,
    step_sessions=21,
    embargo_sessions=0,
    allow_partial_final_test=True,
)
FORMAL_SURFACE_ROWS = 1800
FORMAL_OUTER_FOLD_COUNT = 74
FORMAL_OUTER_STARTS = tuple(range(252, FORMAL_SURFACE_ROWS, 21))
FORMAL_OUTER_POSITION_SCHEDULE_SHA256 = (
    "1d2423311c01397dafca26f7a865be7fb470fd337897e714a8a975a32f559c00"
)
FORMAL_OUTER_COVERAGE_SHA256 = "2cbc336c9ea85a7cbc42af253e6f259940ee748189cdf4f4cc38c66545866f37"
MINIMUM_INNER_OOS_META_ROWS = 252
IDENTITY_SCHEMA = ("date", "session_position")
_PLAN_TOKEN = object()
_TASK_TOKEN = object()


def _normalize_identity(frame: pd.DataFrame, *, context: str) -> pd.DataFrame:
    if tuple(frame.columns) != IDENTITY_SCHEMA or frame.columns.has_duplicates:
        raise StructuralContractError(f"{context} schema must be exactly {IDENTITY_SCHEMA}")
    if frame.empty:
        raise StructuralContractError(f"{context} cannot be empty")
    output = frame.copy()
    output["date"] = normalize_dates(output["date"], context=f"{context}.date").to_numpy(copy=True)
    positions = pd.to_numeric(output["session_position"], errors="coerce").to_numpy(
        dtype=np.float64, na_value=np.nan
    )
    if (
        not np.isfinite(positions).all()
        or not np.equal(positions, np.floor(positions)).all()
        or (positions < 0).any()
        or (np.diff(positions) != 1.0).any()
    ):
        raise StructuralContractError(
            f"{context} session positions must be consecutive non-negative integers"
        )
    output["session_position"] = positions.astype(np.int64)
    if output["date"].duplicated().any() or not output["date"].is_monotonic_increasing:
        raise StructuralContractError(f"{context} dates must be unique and increasing")
    return output.reset_index(drop=True)


def _identity_records(frame: pd.DataFrame) -> tuple[tuple[int, str], ...]:
    return tuple(
        (int(position), pd.Timestamp(date).isoformat())
        for date, position in frame.loc[:, list(IDENTITY_SCHEMA)].itertuples(index=False, name=None)
    )


def _records_frame(records: tuple[tuple[int, str], ...]) -> pd.DataFrame:
    return pd.DataFrame(
        {
            "date": [date for _, date in records],
            "session_position": [position for position, _ in records],
        }
    ).loc[:, list(IDENTITY_SCHEMA)]


@dataclass(frozen=True, init=False)
class NestedOOFTaskPayload:
    """Exact process-safe task identity generated by the plan factory."""

    role: str
    seed: int
    candidate_id: str
    outer_fold_id: str
    task_id: str
    train_records: tuple[tuple[int, str], ...]
    test_records: tuple[tuple[int, str], ...]
    train_end_iso: str
    test_start_iso: str
    test_end_iso: str
    outer_cutoff_iso: str
    base_model_id: str
    base_source_sha256: str
    base_config_sha256: str
    environment_sha256: str
    feature_registry_sha256: str
    train_identity_sha256: str
    test_identity_sha256: str
    task_sha256: str
    design_sha256: str = STRUCTURAL_DESIGN_SHA256

    def __init__(self, *_args: object, **_kwargs: object) -> None:
        raise StructuralContractError("NestedOOFTaskPayload is factory-only")

    @classmethod
    def _mint(cls, *, token: object, **values: Any) -> "NestedOOFTaskPayload":
        if token is not _TASK_TOKEN:
            raise StructuralContractError("invalid nested-task mint token")
        output = object.__new__(cls)
        for key, value in values.items():
            object.__setattr__(output, key, value)
        output._validate()
        return output

    def _validate(self) -> None:
        if self.role not in {"INNER_OOS_FIT", "OUTER_TEST_PREDICT"}:
            raise StructuralContractError("nested task role is invalid")
        if not isinstance(self.seed, int) or isinstance(self.seed, bool):
            raise StructuralContractError("nested task seed must be an integer")
        if not all((self.candidate_id, self.outer_fold_id, self.task_id, self.base_model_id)):
            raise StructuralContractError("nested task identifiers must be non-empty")
        train = _normalize_identity(_records_frame(self.train_records), context="task train")
        test = _normalize_identity(_records_frame(self.test_records), context="task test")
        if int(train["session_position"].max()) >= int(test["session_position"].min()):
            raise StructuralContractError("nested task training must precede its test")
        if pd.Timestamp(train["date"].max()) >= pd.Timestamp(test["date"].min()):
            raise StructuralContractError("nested task dates are not chronological")
        if pd.Timestamp(self.train_end_iso) != pd.Timestamp(train["date"].max()):
            raise StructuralContractError("nested task train end differs from train identity")
        if pd.Timestamp(self.test_start_iso) != pd.Timestamp(test["date"].min()):
            raise StructuralContractError("nested task test start differs from test identity")
        if pd.Timestamp(self.test_end_iso) != pd.Timestamp(test["date"].max()):
            raise StructuralContractError("nested task test end differs from test identity")
        cutoff = normalize_dates([self.outer_cutoff_iso], context="outer cutoff").iloc[0]
        if self.role == "INNER_OOS_FIT" and pd.Timestamp(test["date"].max()) > cutoff:
            raise StructuralContractError("inner task crosses the outer cutoff")
        if self.role == "OUTER_TEST_PREDICT":
            if pd.Timestamp(train["date"].max()) != cutoff:
                raise StructuralContractError("outer task train end differs from outer cutoff")
            if pd.Timestamp(test["date"].min()) <= cutoff:
                raise StructuralContractError("outer task test does not follow outer cutoff")
        for field in (
            "base_source_sha256",
            "base_config_sha256",
            "environment_sha256",
            "feature_registry_sha256",
            "train_identity_sha256",
            "test_identity_sha256",
            "task_sha256",
            "design_sha256",
        ):
            require_sha256(getattr(self, field), field=field)
        if logical_frame_sha256(train) != self.train_identity_sha256:
            raise StructuralContractError("nested task train identity hash changed")
        if logical_frame_sha256(test) != self.test_identity_sha256:
            raise StructuralContractError("nested task test identity hash changed")
        if self.design_sha256 != STRUCTURAL_DESIGN_SHA256:
            raise StructuralContractError("nested task uses a different design")
        if self._computed_sha256() != self.task_sha256:
            raise StructuralContractError("nested task seal changed")

    @property
    def train_positions(self) -> tuple[int, ...]:
        return tuple(position for position, _ in self.train_records)

    @property
    def test_positions(self) -> tuple[int, ...]:
        return tuple(position for position, _ in self.test_records)

    def _unsigned(self) -> dict[str, Any]:
        return {
            "format_version": 2,
            "role": self.role,
            "seed": self.seed,
            "candidate_id": self.candidate_id,
            "outer_fold_id": self.outer_fold_id,
            "task_id": self.task_id,
            "train_records": [[position, date] for position, date in self.train_records],
            "test_records": [[position, date] for position, date in self.test_records],
            "train_end_iso": self.train_end_iso,
            "test_start_iso": self.test_start_iso,
            "test_end_iso": self.test_end_iso,
            "outer_cutoff_iso": self.outer_cutoff_iso,
            "base_model_id": self.base_model_id,
            "base_source_sha256": self.base_source_sha256,
            "base_config_sha256": self.base_config_sha256,
            "environment_sha256": self.environment_sha256,
            "feature_registry_sha256": self.feature_registry_sha256,
            "train_identity_sha256": self.train_identity_sha256,
            "test_identity_sha256": self.test_identity_sha256,
            "design_sha256": self.design_sha256,
        }

    def _computed_sha256(self) -> str:
        return sha256_bytes(canonical_json_bytes(self._unsigned()))

    def to_process_payload(self) -> dict[str, Any]:
        value = self._unsigned()
        value["task_sha256"] = self.task_sha256
        canonical_json_bytes(value)
        return value


def _make_task(
    *,
    role: str,
    seed: int,
    candidate_id: str,
    outer_fold_id: str,
    task_id: str,
    train: pd.DataFrame,
    test: pd.DataFrame,
    outer_cutoff_iso: str,
    base: Any,
) -> NestedOOFTaskPayload:
    values: dict[str, Any] = {
        "role": role,
        "seed": seed,
        "candidate_id": candidate_id,
        "outer_fold_id": outer_fold_id,
        "task_id": task_id,
        "train_records": _identity_records(train),
        "test_records": _identity_records(test),
        "train_end_iso": pd.Timestamp(train["date"].iloc[-1]).isoformat(),
        "test_start_iso": pd.Timestamp(test["date"].iloc[0]).isoformat(),
        "test_end_iso": pd.Timestamp(test["date"].iloc[-1]).isoformat(),
        "outer_cutoff_iso": outer_cutoff_iso,
        "base_model_id": base.model_id,
        "base_source_sha256": base.source_sha256,
        "base_config_sha256": base.config_sha256,
        "environment_sha256": base.environment_sha256,
        "feature_registry_sha256": base.feature_registry_sha256,
        "train_identity_sha256": logical_frame_sha256(train),
        "test_identity_sha256": logical_frame_sha256(test),
        "design_sha256": STRUCTURAL_DESIGN_SHA256,
    }
    provisional = object.__new__(NestedOOFTaskPayload)
    for key, value in values.items():
        object.__setattr__(provisional, key, value)
    values["task_sha256"] = provisional._computed_sha256()
    return NestedOOFTaskPayload._mint(token=_TASK_TOKEN, **values)


@dataclass(frozen=True, init=False)
class NestedOOFPlan:
    """Opaque plan joining outer identity, every task, and exact base replay."""

    seed: int
    candidate_id: str
    outer_fold_id: str
    outer_cutoff_iso: str
    base_model_id: str
    base_source_sha256: str
    base_config_sha256: str
    environment_sha256: str
    feature_registry_sha256: str
    authorization_sha256: str
    outer_train_records: tuple[tuple[int, str], ...]
    outer_test_records: tuple[tuple[int, str], ...]
    outer_train_identity_sha256: str
    outer_test_identity_sha256: str
    tasks: tuple[NestedOOFTaskPayload, ...]
    outer_task: NestedOOFTaskPayload
    meta_session_positions: tuple[int, ...]
    task_manifest_sha256: str
    fold_sha256: str
    plan_sha256: str
    minimum_meta_rows: int
    design_sha256: str
    formal_schedule_sha256: str | None
    formal_surface_identity_sha256: str | None
    formal_fold_index: int | None
    formal_fold_count: int | None

    def __init__(self, *_args: object, **_kwargs: object) -> None:
        raise StructuralContractError("NestedOOFPlan is factory-only")

    @classmethod
    def _mint(cls, *, token: object, **values: Any) -> "NestedOOFPlan":
        if token is not _PLAN_TOKEN:
            raise StructuralContractError("invalid nested-plan mint token")
        output = object.__new__(cls)
        for key, value in values.items():
            object.__setattr__(output, key, value)
        return output

    @property
    def meta_row_count(self) -> int:
        return len(self.meta_session_positions)

    @property
    def eligible_for_formal_meta_fit(self) -> bool:
        return self.meta_row_count >= self.minimum_meta_rows

    def _unsigned(self) -> dict[str, Any]:
        return {
            "format_version": 2,
            "mode": "factory_only_executable_nested_oof_plan",
            "seed": self.seed,
            "candidate_id": self.candidate_id,
            "outer_fold_id": self.outer_fold_id,
            "outer_cutoff_iso": self.outer_cutoff_iso,
            "base_model_id": self.base_model_id,
            "base_source_sha256": self.base_source_sha256,
            "base_config_sha256": self.base_config_sha256,
            "environment_sha256": self.environment_sha256,
            "feature_registry_sha256": self.feature_registry_sha256,
            "authorization_sha256": self.authorization_sha256,
            "outer_train_records": [list(item) for item in self.outer_train_records],
            "outer_test_records": [list(item) for item in self.outer_test_records],
            "outer_train_identity_sha256": self.outer_train_identity_sha256,
            "outer_test_identity_sha256": self.outer_test_identity_sha256,
            "tasks": [task.to_process_payload() for task in self.tasks],
            "outer_task": self.outer_task.to_process_payload(),
            "meta_session_positions": list(self.meta_session_positions),
            "task_manifest_sha256": self.task_manifest_sha256,
            "fold_sha256": self.fold_sha256,
            "minimum_meta_rows": self.minimum_meta_rows,
            "design_sha256": self.design_sha256,
            "formal_schedule_sha256": self.formal_schedule_sha256,
            "formal_surface_identity_sha256": self.formal_surface_identity_sha256,
            "formal_fold_index": self.formal_fold_index,
            "formal_fold_count": self.formal_fold_count,
        }

    def to_sealed_payload(self) -> dict[str, Any]:
        value = self._unsigned()
        value["plan_sha256"] = self.plan_sha256
        canonical_json_bytes(value)
        return value

    def verify(self, authorization: StructuralExecutionAuthorization) -> None:
        if not isinstance(authorization, StructuralExecutionAuthorization):
            raise StructuralContractError("nested plan requires sealed authorization")
        authorization.verify()
        if self.design_sha256 != STRUCTURAL_DESIGN_SHA256:
            raise StructuralContractError("nested plan design changed")
        if self.minimum_meta_rows != MINIMUM_INNER_OOS_META_ROWS:
            raise StructuralContractError("nested minimum meta rows changed")
        if self.authorization_sha256 != authorization.authorization_sha256:
            raise StructuralContractError("nested plan authorization changed")
        if authorization.scope == "FORMAL_SPENT":
            if (
                self.formal_schedule_sha256 is None
                or self.formal_surface_identity_sha256 is None
                or self.formal_fold_index is None
                or self.formal_fold_count != FORMAL_OUTER_FOLD_COUNT
                or self.formal_schedule_sha256 != FORMAL_OUTER_POSITION_SCHEDULE_SHA256
                or self.formal_fold_index not in range(FORMAL_OUTER_FOLD_COUNT)
                or self.outer_fold_id != f"fold_{self.formal_fold_index:03d}"
                or self.outer_task.test_positions[0] != FORMAL_OUTER_STARTS[self.formal_fold_index]
            ):
                raise StructuralContractError("formal plan is not on the code-owned outer schedule")
        elif any(
            value is not None
            for value in (
                self.formal_schedule_sha256,
                self.formal_surface_identity_sha256,
                self.formal_fold_index,
                self.formal_fold_count,
            )
        ):
            raise StructuralContractError("synthetic plan cannot claim formal schedule provenance")
        base = _authorized_base(authorization, self.candidate_id, self.base_model_id)
        actual_binding = (
            self.base_source_sha256,
            self.base_config_sha256,
            self.environment_sha256,
            self.feature_registry_sha256,
        )
        expected_binding = (
            base.source_sha256,
            base.config_sha256,
            base.environment_sha256,
            base.feature_registry_sha256,
        )
        if actual_binding != expected_binding:
            raise StructuralContractError("nested plan exact base replay binding changed")
        train = _normalize_identity(
            _records_frame(self.outer_train_records), context="plan outer train"
        )
        test = _normalize_identity(
            _records_frame(self.outer_test_records), context="plan outer test"
        )
        if logical_frame_sha256(train) != self.outer_train_identity_sha256:
            raise StructuralContractError("nested plan outer-train identity changed")
        if logical_frame_sha256(test) != self.outer_test_identity_sha256:
            raise StructuralContractError("nested plan outer-test identity changed")
        cutoff = normalize_dates([self.outer_cutoff_iso], context="plan cutoff").iloc[0]
        if pd.Timestamp(train["date"].iloc[-1]) != cutoff:
            raise StructuralContractError("nested plan cutoff differs from outer train")
        if pd.Timestamp(test["date"].iloc[0]) <= cutoff:
            raise StructuralContractError("nested plan outer test does not follow cutoff")
        if any(task.role != "INNER_OOS_FIT" for task in self.tasks):
            raise StructuralContractError("nested plan contains a non-inner task")
        if self.outer_task.role != "OUTER_TEST_PREDICT":
            raise StructuralContractError("nested plan outer task role changed")
        flattened = tuple(position for task in self.tasks for position in task.test_positions)
        if flattened != self.meta_session_positions:
            raise StructuralContractError("nested plan meta positions differ from tasks")
        task_payloads = [task.to_process_payload() for task in self.tasks]
        if sha256_bytes(canonical_json_bytes(task_payloads)) != self.task_manifest_sha256:
            raise StructuralContractError("nested plan task manifest changed")
        fold_payload = {
            "inner_task_sha256s": [task.task_sha256 for task in self.tasks],
            "outer_task_sha256": self.outer_task.task_sha256,
            "outer_train_identity_sha256": self.outer_train_identity_sha256,
            "outer_test_identity_sha256": self.outer_test_identity_sha256,
            "outer_cutoff_iso": self.outer_cutoff_iso,
        }
        if sha256_bytes(canonical_json_bytes(fold_payload)) != self.fold_sha256:
            raise StructuralContractError("nested plan fold/provenance hash changed")
        if sha256_bytes(canonical_json_bytes(self._unsigned())) != self.plan_sha256:
            raise StructuralContractError("nested plan seal changed")


def _authorized_base(
    authorization: StructuralExecutionAuthorization,
    candidate_id: str,
    base_model_id: str,
):
    if candidate_id == "residual_ar1_nested_oof":
        return authorization.require_residual_base(candidate_id, base_model_id)
    if candidate_id in {"stack_geometric_equal_pair", "stack_simplex_pair_frozen"}:
        pair = authorization.require_pair(
            candidate_id, authorization.pair[0].model_id, authorization.pair[1].model_id
        )
        matches = [item for item in pair if item.model_id == base_model_id]
        if len(matches) != 1:
            raise StructuralContractError("nested plan base is not in the exact selected pair")
        return matches[0]
    raise StructuralContractError("candidate does not admit nested base artifacts")


def _build_nested_oof_plan(
    outer_train_frame: pd.DataFrame,
    outer_test_frame: pd.DataFrame,
    *,
    seed: int,
    outer_fold_id: str,
    outer_cutoff: object,
    candidate_id: str,
    base_model_id: str,
    authorization: StructuralExecutionAuthorization,
    formal_schedule_sha256: str | None = None,
    formal_surface_identity_sha256: str | None = None,
    formal_fold_index: int | None = None,
    formal_fold_count: int | None = None,
) -> NestedOOFPlan:
    """Create a plan with exact identities and authorization-derived base hashes."""

    if not isinstance(authorization, StructuralExecutionAuthorization):
        raise StructuralContractError("nested plan factory requires sealed authorization")
    base = _authorized_base(authorization, candidate_id, base_model_id)
    train = _normalize_identity(outer_train_frame, context="outer train")
    test = _normalize_identity(outer_test_frame, context="outer test")
    if int(train["session_position"].max()) >= int(test["session_position"].min()):
        raise StructuralContractError("outer training positions must precede outer test")
    cutoff = normalize_dates([outer_cutoff], context="outer cutoff").iloc[0]
    if pd.Timestamp(train["date"].iloc[-1]) != cutoff:
        raise StructuralContractError("outer cutoff must equal last outer-training date")
    if pd.Timestamp(test["date"].iloc[0]) <= cutoff:
        raise StructuralContractError("outer test must strictly follow cutoff")
    if not isinstance(seed, int) or isinstance(seed, bool) or not outer_fold_id:
        raise StructuralContractError("outer seed/fold identity is invalid")

    local = pd.DataFrame({"date": train["date"].to_numpy(copy=True)})
    try:
        folds = generate_pit_folds(local, NESTED_FOLD_SPEC, date_column="date")
    except Exception:
        if len(local) >= NESTED_FOLD_SPEC.min_train_sessions + NESTED_FOLD_SPEC.test_sessions:
            raise
        folds = ()
    tasks: list[NestedOOFTaskPayload] = []
    for index, fold in enumerate(folds):
        tasks.append(
            _make_task(
                role="INNER_OOS_FIT",
                seed=seed,
                candidate_id=candidate_id,
                outer_fold_id=outer_fold_id,
                task_id=f"{outer_fold_id}__inner_{index:03d}",
                train=train.iloc[list(fold.train_positions)].reset_index(drop=True),
                test=train.iloc[list(fold.test_positions)].reset_index(drop=True),
                outer_cutoff_iso=pd.Timestamp(cutoff).isoformat(),
                base=base,
            )
        )
    outer_task = _make_task(
        role="OUTER_TEST_PREDICT",
        seed=seed,
        candidate_id=candidate_id,
        outer_fold_id=outer_fold_id,
        task_id=f"{outer_fold_id}__outer_test",
        train=train,
        test=test,
        outer_cutoff_iso=pd.Timestamp(cutoff).isoformat(),
        base=base,
    )
    task_manifest = sha256_bytes(
        canonical_json_bytes([task.to_process_payload() for task in tasks])
    )
    outer_train_hash = logical_frame_sha256(train)
    outer_test_hash = logical_frame_sha256(test)
    fold_payload = {
        "inner_task_sha256s": [task.task_sha256 for task in tasks],
        "outer_task_sha256": outer_task.task_sha256,
        "outer_train_identity_sha256": outer_train_hash,
        "outer_test_identity_sha256": outer_test_hash,
        "outer_cutoff_iso": pd.Timestamp(cutoff).isoformat(),
    }
    values: dict[str, Any] = {
        "seed": seed,
        "candidate_id": candidate_id,
        "outer_fold_id": outer_fold_id,
        "outer_cutoff_iso": pd.Timestamp(cutoff).isoformat(),
        "base_model_id": base.model_id,
        "base_source_sha256": base.source_sha256,
        "base_config_sha256": base.config_sha256,
        "environment_sha256": base.environment_sha256,
        "feature_registry_sha256": base.feature_registry_sha256,
        "authorization_sha256": authorization.authorization_sha256,
        "outer_train_records": _identity_records(train),
        "outer_test_records": _identity_records(test),
        "outer_train_identity_sha256": outer_train_hash,
        "outer_test_identity_sha256": outer_test_hash,
        "tasks": tuple(tasks),
        "outer_task": outer_task,
        "meta_session_positions": tuple(
            position for task in tasks for position in task.test_positions
        ),
        "task_manifest_sha256": task_manifest,
        "fold_sha256": sha256_bytes(canonical_json_bytes(fold_payload)),
        "minimum_meta_rows": MINIMUM_INNER_OOS_META_ROWS,
        "design_sha256": STRUCTURAL_DESIGN_SHA256,
        "formal_schedule_sha256": formal_schedule_sha256,
        "formal_surface_identity_sha256": formal_surface_identity_sha256,
        "formal_fold_index": formal_fold_index,
        "formal_fold_count": formal_fold_count,
    }
    provisional = NestedOOFPlan._mint(token=_PLAN_TOKEN, **values, plan_sha256="0" * 64)
    values["plan_sha256"] = sha256_bytes(canonical_json_bytes(provisional._unsigned()))
    output = NestedOOFPlan._mint(token=_PLAN_TOKEN, **values)
    output.verify(authorization)
    return output


def formal_fold_id_for_test_start(test_start_position: int) -> str:
    """Resolve only one of the 74 code-owned outer starts; 601 is invalid."""

    if (
        not isinstance(test_start_position, int)
        or isinstance(test_start_position, bool)
        or test_start_position not in FORMAL_OUTER_STARTS
    ):
        raise StructuralContractError("formal outer test start is off the code-owned grid")
    return f"fold_{FORMAL_OUTER_STARTS.index(test_start_position):03d}"


def build_nested_oof_plan(
    outer_train_frame: pd.DataFrame,
    outer_test_frame: pd.DataFrame,
    *,
    seed: int,
    outer_fold_id: str,
    outer_cutoff: object,
    candidate_id: str,
    base_model_id: str,
    authorization: StructuralExecutionAuthorization,
) -> NestedOOFPlan:
    """Synthetic-only plan factory; formal callers must select a sealed fold ID."""

    if authorization.scope != "SYNTHETIC_NO_SCORE":
        raise StructuralContractError(
            "formal plans require build_formal_nested_oof_plan and code-owned membership"
        )
    return _build_nested_oof_plan(
        outer_train_frame,
        outer_test_frame,
        seed=seed,
        outer_fold_id=outer_fold_id,
        outer_cutoff=outer_cutoff,
        candidate_id=candidate_id,
        base_model_id=base_model_id,
        authorization=authorization,
    )


def build_formal_nested_oof_plan(
    *,
    seed: int,
    outer_fold_id: str,
    candidate_id: str,
    base_model_id: str,
    authorization: StructuralExecutionAuthorization,
) -> NestedOOFPlan:
    """Reconstruct one entire exact fold from the sealed 1,800-row spent surface."""

    authorization.require_formal_spent_go()
    if not isinstance(outer_fold_id, str) or not outer_fold_id.startswith("fold_"):
        raise StructuralContractError("formal outer fold ID is invalid")
    try:
        fold_index = int(outer_fold_id.removeprefix("fold_"))
    except ValueError as exc:
        raise StructuralContractError("formal outer fold ID is invalid") from exc
    if outer_fold_id != f"fold_{fold_index:03d}" or fold_index not in range(
        FORMAL_OUTER_FOLD_COUNT
    ):
        raise StructuralContractError("formal outer fold is outside the exact 74-fold schedule")

    from ..models.wave1.artifacts import inspect_predict_seed_entry, load_predict_inputs

    manifest = load_predict_inputs(
        authorization.project_root / "outputs/model_zoo_wave1_screen_20260819/PREDICT_INPUTS.json"
    )
    entries = [row for row in manifest["seeds"] if int(row["seed"]) == seed]
    if len(entries) != 1:
        raise StructuralContractError("formal seed is outside the sealed spent universe")
    inspected = inspect_predict_seed_entry(entries[0])
    dates = pd.to_datetime(inspected["dates"], errors="raise")
    if len(dates) != FORMAL_SURFACE_ROWS:
        raise StructuralContractError("formal identity surface must contain exactly 1,800 rows")
    identity = pd.DataFrame(
        {"date": dates.to_numpy(copy=True), "session_position": np.arange(len(dates))}
    )
    folds = generate_pit_folds(identity, FORMAL_OUTER_FOLD_SPEC, date_column="date")
    position_payload = [
        {
            "fold_id": fold.fold_id,
            "train_positions": list(fold.train_positions),
            "test_positions": list(fold.test_positions),
        }
        for fold in folds
    ]
    coverage = [position for fold in folds for position in fold.test_positions]
    if (
        len(folds) != FORMAL_OUTER_FOLD_COUNT
        or tuple(fold.test_positions[0] for fold in folds) != FORMAL_OUTER_STARTS
        or len(folds[-1].test_positions) != 15
        or sha256_bytes(canonical_json_bytes(position_payload))
        != FORMAL_OUTER_POSITION_SCHEDULE_SHA256
        or sha256_bytes(canonical_json_bytes(coverage)) != FORMAL_OUTER_COVERAGE_SHA256
        or coverage != list(range(252, FORMAL_SURFACE_ROWS))
    ):
        raise StructuralContractError("formal outer schedule/coverage reconstruction changed")
    fold = folds[fold_index]
    if fold.fold_id != outer_fold_id:
        raise StructuralContractError("formal fold ID/member mapping changed")
    train = identity.iloc[list(fold.train_positions)].reset_index(drop=True)
    test = identity.iloc[list(fold.test_positions)].reset_index(drop=True)
    return _build_nested_oof_plan(
        train,
        test,
        seed=seed,
        outer_fold_id=fold.fold_id,
        outer_cutoff=fold.train_end,
        candidate_id=candidate_id,
        base_model_id=base_model_id,
        authorization=authorization,
        formal_schedule_sha256=FORMAL_OUTER_POSITION_SCHEDULE_SHA256,
        formal_surface_identity_sha256=logical_frame_sha256(identity),
        formal_fold_index=fold_index,
        formal_fold_count=FORMAL_OUTER_FOLD_COUNT,
    )
