"""Truth-free PE-C4 H-OFS V12 service with an exact live resource gate."""

from .contracts import (
    ACTUAL_COMMON_PATH_BINDING_STATUS,
    CANDIDATE_ID,
    DGP_IDS,
    ExternalTaskBinding,
    HOFS_TASK_SURFACE_COLUMNS,
    HofsV12QualificationServiceError,
    QUALIFICATION_SEEDS,
    QUALIFICATION_SEED_TO_ALIAS,
    PRODUCTION_NUMERIC_AUTHORITY_STATUS,
    SEED_ALIASES,
    SOURCE_MODEL_VERSION_BINDING_STATUS,
    SPENT_RESEARCH_ONLY_CANONICAL_RAW_SHA256,
    SPENT_RESEARCH_ONLY_DGP_ID,
    SPENT_RESEARCH_ONLY_SEED,
    SPENT_RESEARCH_ONLY_SEED_ALIAS,
    TASK_COUNT,
    WORKER_AFFINITY_MASK,
    V7_RUNTIME_ENVELOPE_CONFLICT_ID,
    build_qualification_fold_plan,
    build_source_model_version,
    contract_payload,
)
from .runtime import (
    RuntimePrebindingArtifact,
    build_isolated_c4_runtime_prebinding,
    build_task_worker_assignments,
    build_worker_slot_plan,
    current_windows_process_memory,
    expected_process_exit_records,
    run_native_16_worker_resource_preflight,
    validate_current_worker_envelope,
    validate_inherited_gpu_off_environment,
    validate_live_resource_values,
)
from .publisher import validate_spent_evidence_receipts
from .service import (
    ComputedTaskArtifact,
    InputValidationReceipt,
    ValidatedTaskInput,
    V7DecisionBlockResult,
    compute_task_artifact,
    compute_task_surface,
    compute_spent_research_only_task_artifact,
    validate_exact_task_universe,
    validate_injected_task,
    validate_task_surface,
)


__all__ = [
    "ACTUAL_COMMON_PATH_BINDING_STATUS",
    "CANDIDATE_ID",
    "ComputedTaskArtifact",
    "DGP_IDS",
    "ExternalTaskBinding",
    "HOFS_TASK_SURFACE_COLUMNS",
    "HofsV12QualificationServiceError",
    "InputValidationReceipt",
    "QUALIFICATION_SEEDS",
    "QUALIFICATION_SEED_TO_ALIAS",
    "PRODUCTION_NUMERIC_AUTHORITY_STATUS",
    "RuntimePrebindingArtifact",
    "SEED_ALIASES",
    "SOURCE_MODEL_VERSION_BINDING_STATUS",
    "SPENT_RESEARCH_ONLY_CANONICAL_RAW_SHA256",
    "SPENT_RESEARCH_ONLY_DGP_ID",
    "SPENT_RESEARCH_ONLY_SEED",
    "SPENT_RESEARCH_ONLY_SEED_ALIAS",
    "TASK_COUNT",
    "V7DecisionBlockResult",
    "V7_RUNTIME_ENVELOPE_CONFLICT_ID",
    "WORKER_AFFINITY_MASK",
    "ValidatedTaskInput",
    "build_isolated_c4_runtime_prebinding",
    "build_qualification_fold_plan",
    "build_source_model_version",
    "build_task_worker_assignments",
    "build_worker_slot_plan",
    "compute_task_artifact",
    "compute_task_surface",
    "compute_spent_research_only_task_artifact",
    "contract_payload",
    "current_windows_process_memory",
    "expected_process_exit_records",
    "run_native_16_worker_resource_preflight",
    "validate_current_worker_envelope",
    "validate_exact_task_universe",
    "validate_inherited_gpu_off_environment",
    "validate_injected_task",
    "validate_task_surface",
    "validate_live_resource_values",
    "validate_spent_evidence_receipts",
]
