"""Isolated score-free H-OFS V7 repair capability."""

from .contracts import (
    CANDIDATE,
    CANDIDATE_ID,
    IDENTITY_COLUMNS,
    MODEL_FEATURE_COLUMNS,
    OUTPUT_COLUMNS,
    PARENT_FEATURE_CONTRACT_SHA256,
    PARENT_RUNTIME_SOURCE_SHA256,
    R4_INPUT_BINDING,
    V4_DESIGN_FREEZE_BINDING,
    V4_INDEPENDENT_AUDIT_BINDING,
    V5_DESIGN_FREEZE_BINDING,
    V5_INDEPENDENT_AUDIT_BINDING,
    V6_DESIGN_FREEZE_BINDING,
    V6_INDEPENDENT_AUDIT_BINDING,
    V6_ZERO_FIT_FAILURE_EVIDENCE,
    HierarchicalStateV7ContractError,
    contract_payload,
    contract_sha256,
)
from .adapter import (
    DecisionBatchV7,
    HierarchicalModelOutputV7,
    apply_frozen_parameters_v7,
    decision_block_ordered_membership_sha256_v7,
    decision_block_set_membership_sha256_v7,
    decision_source_positions_sha256_v7,
)
from .custody import require_canonical_decision_identity_order_v7
from .dgp_r4 import (
    R4FoldSpecV7,
    adapt_r4_canonical_source_v7,
    build_r4_fold_plan_v7,
    build_r4_input_closure_v7,
)
from .artifacts import (
    PARAMETER_BUNDLE_FILES,
    build_frozen_parameter_bundle_bytes,
    load_frozen_parameter_bundle,
)
from .estimator import (
    FitReceiptV7,
    FrozenHierarchicalParametersV7,
    HierarchicalFitResultV7,
    fit_config_sha256,
    fit_hierarchical_state_v7,
    causal_training_valid_mask_v7,
)
from .features import (
    HierarchicalStateFrameV7,
    bind_research_dgp_nuisance_groups_v7,
    build_hierarchical_state_features_v7,
    validate_bound_identities,
    validate_research_dgp_nuisance_groups_v7,
)
from .runtime import ResourceReceiptV7, capture_runtime_receipt_v7
from .runner import (
    ChronologicalFitCapabilityResultV7,
    build_decision_batch_v7,
    fit_chronological_prefix_v7,
    load_and_run_frozen_decision_block_v7,
    run_frozen_decision_block_v7,
)
from .source_audit import SourceAuditResultV7, run_source_audit_v7

__all__ = [
    "CANDIDATE",
    "CANDIDATE_ID",
    "ChronologicalFitCapabilityResultV7",
    "DecisionBatchV7",
    "FitReceiptV7",
    "FrozenHierarchicalParametersV7",
    "HierarchicalFitResultV7",
    "HierarchicalModelOutputV7",
    "HierarchicalStateFrameV7",
    "HierarchicalStateV7ContractError",
    "IDENTITY_COLUMNS",
    "MODEL_FEATURE_COLUMNS",
    "OUTPUT_COLUMNS",
    "PARAMETER_BUNDLE_FILES",
    "PARENT_FEATURE_CONTRACT_SHA256",
    "PARENT_RUNTIME_SOURCE_SHA256",
    "ResourceReceiptV7",
    "R4FoldSpecV7",
    "R4_INPUT_BINDING",
    "SourceAuditResultV7",
    "V4_DESIGN_FREEZE_BINDING",
    "V4_INDEPENDENT_AUDIT_BINDING",
    "V5_DESIGN_FREEZE_BINDING",
    "V5_INDEPENDENT_AUDIT_BINDING",
    "V6_DESIGN_FREEZE_BINDING",
    "V6_INDEPENDENT_AUDIT_BINDING",
    "V6_ZERO_FIT_FAILURE_EVIDENCE",
    "adapt_r4_canonical_source_v7",
    "apply_frozen_parameters_v7",
    "bind_research_dgp_nuisance_groups_v7",
    "build_decision_batch_v7",
    "build_frozen_parameter_bundle_bytes",
    "build_hierarchical_state_features_v7",
    "build_r4_fold_plan_v7",
    "build_r4_input_closure_v7",
    "contract_payload",
    "contract_sha256",
    "capture_runtime_receipt_v7",
    "causal_training_valid_mask_v7",
    "decision_block_ordered_membership_sha256_v7",
    "decision_block_set_membership_sha256_v7",
    "decision_source_positions_sha256_v7",
    "fit_chronological_prefix_v7",
    "fit_config_sha256",
    "fit_hierarchical_state_v7",
    "load_and_run_frozen_decision_block_v7",
    "load_frozen_parameter_bundle",
    "run_frozen_decision_block_v7",
    "run_source_audit_v7",
    "require_canonical_decision_identity_order_v7",
    "validate_bound_identities",
    "validate_research_dgp_nuisance_groups_v7",
]
